#############################################################################
# Makefile for building: QtLog
# Generated by qmake (3.1) (Qt 6.8.0)
# Project:  QtLog.pro
# Template: lib
# Command: D:\tools\Qt\6.8.0\msvc2022_64\bin\qmake.exe -o Makefile QtLog.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\tools\Qt\6.8.0\msvc2022_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\tools\Qt\6.8.0\msvc2022_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\tools\Qt\6.8.0\msvc2022_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: QtLog.pro ..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\win32-msvc\qmake.conf ..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_pre.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-desktop.conf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-vulkan.conf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-desktop.conf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\qconfig.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_functions.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_config.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\win32-msvc\qmake.conf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-version.conf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\toolchain.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\default_pre.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\default_pre.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\resolve_config.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\default_post.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qtquickcompiler.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\precompile_header.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\warn_on.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\permissions.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qt.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\resources_functions.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\resources.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\moc.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qmake_use.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\file_copies.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\testcase_targets.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\exceptions.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\yacc.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\lex.prf \
		QtLog.pro \
		..\..\tools\Qt\6.8.0\msvc2022_64\lib\Qt6Core.prl \
		..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\build_pass.prf \
		..\..\tools\Qt\6.8.0\msvc2022_64\lib\Qt6Cored.prl
	$(QMAKE) -o Makefile QtLog.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_pre.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-desktop.conf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\windows-vulkan.conf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-desktop.conf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\qconfig.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_functions.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qt_config.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\win32-msvc\qmake.conf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\common\msvc-version.conf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\toolchain.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\default_pre.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\default_pre.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\resolve_config.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\exclusive_builds_post.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\default_post.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qtquickcompiler.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\precompile_header.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\warn_on.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\permissions.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qt.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\resources_functions.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\resources.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\moc.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\qmake_use.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\file_copies.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\win32\windows.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\testcase_targets.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\exceptions.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\yacc.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\lex.prf:
QtLog.pro:
..\..\tools\Qt\6.8.0\msvc2022_64\lib\Qt6Core.prl:
..\..\tools\Qt\6.8.0\msvc2022_64\mkspecs\features\build_pass.prf:
..\..\tools\Qt\6.8.0\msvc2022_64\lib\Qt6Cored.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QtLog.pro -spec win32-msvc "CONFIG+=qtquickcompiler"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
	-$(DEL_FILE) bin\QtLog.exp
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash bin\QtLog.lib

dummy:
	mkdir D:/pro/QtLog/include & mkdir D:/pro/QtLog/bin & mkdir D:/pro/QtLog/lib

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
